apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskly-demo
  labels:
    app: taskly-demo
spec:
  selector:
    matchLabels:
      app: taskly-demo
  template:
    metadata:
      labels:
        app: taskly-demo
        tier: web
    spec:
      containers:
      - name: taskly-demo
        image: gcr.io/proton-wallet/proton-taskly-demo@sha256:24f547d5eac62858b2df9a696ee956d21fa55e663a0db44bc13d8fdccfa19b69
        ports:
        - containerPort: 3000